repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: poetry run poe format
    language: system
    types: [python]
  - id: flake8
    name: flake8
    entry: poetry run poe lint
    language: system
    types: [python]